### ISSUE TITLE
Decode URL params

### ISSUE THREAD

**Issue by ivan-tymoshenko** [prostojs/router#1]
We can discuss it here.

**Comment by mav-rik** [comment]
@ivan-tymoshenko the current state is:

```ts
        const router = new ProstoRouter()
        const handler = () => {}
        router.get('/🍌/:id', handler)

        console.log(router.toTree())
                
        expect((router.find('GET', `/%F0%9F%8D%8C/${singleEncode('#')}`)).ctx.params['id']).toEqual('#')
        expect((router.find('GET', `/%F0%9F%8D%8C/${doubleEncode('#')}`)).ctx.params['id']).toEqual(singleEncode('#'))
```

Both expectations are met.
Do you see any further issues with the way it handles paths?

**Comment by ivan-tymoshenko** [comment]
```js
const router = new ProstoRouter()
const handler = () => {}
router.get('/:id/🍌', handler)

console.log(router.toTree())
                
expect((router.find('GET', `/${singleEncode('#')}/%F0%9F%8D%8C`)).ctx.params['id']).toEqual('#')
expect((router.find('GET', `/${doubleEncode('#')}/%F0%9F%8D%8C`)).ctx.params['id']).toEqual(singleEncode('#'))
```

Does it also work? I'm sorry, can't test by myself. I can't even install deps.

**Comment by mav-rik** [comment]
@ivan-tymoshenko yes it does. Added this to test file as well.

**Comment by mav-rik** [comment]
@ivan-tymoshenko published v0.0.9

**Comment by ivan-tymoshenko** [comment]
```js
const { ProstoRouter } = require('@prostojs/router')

const router = new ProstoRouter()

router.on('GET', '/🍌/:param', () => 'ok')
console.log(router.lookup('GET', '/🍌/test')) // undefined
```

**Comment by mav-rik** [comment]
@ivan-tymoshenko according to [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986) the URI contains only ASCII characters. All the rest is encoded in %-notation. So you must call "lookup" method with proper URI. In this case it must be `'/%F0%9F%8D%8C/test'`.

I don't find it necessary to cover up such synthetic cases because the main purpose for this lib is to resolve URI transferred over HTTP which is impossible to be in UTF-8.

**Comment by ivan-tymoshenko** [comment]
ok
```js
const { ProstoRouter } = require('@prostojs/router')

const router = new ProstoRouter()

router.on('GET', '/~/:param', () => 'ok')
console.log(router.lookup('GET', '/%7E/test')) // undefined
```

**Comment by mav-rik** [comment]
@ivan-tymoshenko alright, that one (~) is more tricky. `encodeURI('~')` returns `'~'`. So the browser shouldn't encode that character. Although I assume we must take `'/~'` and `'/%7E` as the same URI. I'll see what I can do about it.

**Comment by ivan-tymoshenko** [comment]
It's an example from your issue, where you said that according to the RFC '~' === ''%7e'. And where you said that we never should use the encodeURI function when setting a route. And technically you did it right now in your fix.

https://github.com/delvedor/find-my-way/issues/206#issue-1016799776

**Comment by mav-rik** [comment]
@ivan-tymoshenko nice one. Looks like I'm running in circle.

**Comment by ivan-tymoshenko** [comment]
I spent some time trying to deal with it. What I can tell you is there is no good way to do this. What I suggested in the PR I tagged you is to add the `encode` option. When it equals true, we will encode static parts of the route before inserting it (just like in your fix). And there also '~' not equal to '%7e'. If you want to match '/%7e', you need to set the route manually '/%7e'.

path-to-regexp works in the same way.

 If you find out a better solution, please ping me here. If not please come back to the PR (https://github.com/delvedor/find-my-way/pull/253) and write a short conclusion about it. It would be really important because not everyone has time to go deep into this question and your opinion would be important, bc you are the one who found the problem and raise the issue (https://github.com/delvedor/find-my-way/issues/206).
 
Thanks for your help.

**Comment by mav-rik** [comment]
@ivan-tymoshenko yes I can understand the depth of the problem now.

And I think I agree with my 206 comment that we shouldn't ever encodeURI when setting a route because by doing so we bring so much of inconsistency to the URI resolving procedure. I will try to find a better solution.

Thank you for this challenge.

**Comment by mav-rik** [comment]
@ivan-tymoshenko I think I found a solution.

Initially everything worked fine except double decoding part. So I reverted everything to how it was before.

Then, as long as the issue is only with double decoding, which can only happen when you use `%25` in URI, I added one more thing to URI normalization process.

I replace `%25` with some unique characters sequence in order to avoid it to be decoded if first place.
When setting up a route if it contains `%` I replace it as well (in order to keep it to matching to normalized URIs).

And when I do decode params I first replace unique characters sequence back to `%25` and then do `decodeURIComponent` - so the decode for that particular one happens only once.

All the previous test cases pass.

I deployed v0.0.10

**Comment by ivan-tymoshenko** [comment]
What if I set up to routes like this?
```js
router.on('GET', '/‣PRC⁑', () => 'ok')
router.on('GET', '/%', () => 'ok')
```

**Comment by ivan-tymoshenko** [comment]
This is also works but it shouldn't
```js
router.on('GET', '/%', () => 'ok')
router.lookup('GET', '/‣PRC⁑')
```

**Comment by mav-rik** [comment]
@ivan-tymoshenko of course this is the downside.

1) `/‣PRC⁑` and `/%` are identical due to implementation (I might find some better characters combination in future)
2) The combination used for replacement should be never used (I might deprecate it on lib level)
3) `router.lookup('GET', '/‣PRC⁑')` - here you use incorrect URI, as I said earlier URI can only contain ASCII symbols. All the rest characters are to be encoded with %-notation. So there is no way to send UTF-8 chars in HTTP request header .

**Comment by ivan-tymoshenko** [comment]
It's a vulnerability right now. I can set `router.on('GET', '/%', () => 'ok')` and can get it by `router.lookup('GET', '/‣PRC⁑')`. It can help to get through some security filters.

**Comment by ivan-tymoshenko** [comment]
> @ivan-tymoshenko of course this is the downside.
> 
> 1. `/‣PRC⁑` and `/%` are identical due to implementation (I might find some better characters combination in future)
> 2. The combination used for replacement should be never used (I might deprecate it on lib level)
> 3. `router.lookup('GET', '/‣PRC⁑')` - here you use incorrect URI, as I said earlier URI can only contain ASCII symbols. All the rest characters are to be encoded with %-notation. So there is no way to send UTF-8 chars in HTTP request header .

And you think that it's a good solution? Restrict some path combinations?

**Comment by mav-rik** [comment]
Where do you get `'/‣PRC⁑'` from as an input? It can not be http request header. What's the use-case?

**Comment by mav-rik** [comment]
> > @ivan-tymoshenko of course this is the downside.
> > 
> > 1. `/‣PRC⁑` and `/%` are identical due to implementation (I might find some better characters combination in future)
> > 2. The combination used for replacement should be never used (I might deprecate it on lib level)
> > 3. `router.lookup('GET', '/‣PRC⁑')` - here you use incorrect URI, as I said earlier URI can only contain ASCII symbols. All the rest characters are to be encoded with %-notation. So there is no way to send UTF-8 chars in HTTP request header .
> 
> And you think that it's a good solution? Restrict some path combinations?

Yes I think it's the best I could find. Do you have any better solution?

**Comment by ivan-tymoshenko** [comment]
First of all, it doesn't matter. If you don't use it, it doesn't mean that someone can't. If we will follow this logic, I can ask you why someone will use '%7E' instead of '~'.

**Comment by ivan-tymoshenko** [comment]
Secondly, as I told you I can put this combination manually instead of "%" to get through some security filters.

**Comment by mav-rik** [comment]
@ivan-tymoshenko I follow the RFC 3986 and the purpose of the lib is to provide a solid, fast and robust way of routing URIs to proper handlers. The input for `lookup` method is intended to be a HTTP request header. I can't get what kind of use-cases you're trying to cover.

**Comment by mav-rik** [comment]
Yes you can send `~` as well as `%7E` using browser string or whatever lib like axios. You can even send `'%31%32%33'` which is the same as `'123'`. This all should work fine. But you can not send request with URI like `‣PRC⁑` - simply no possible via HTTP request.

**Comment by ivan-tymoshenko** [comment]
```js
const http = require('http')
const { ProstoRouter } = require('@prostojs/router')

const router = new ProstoRouter()

router.on('GET', '/%', () => 'ok' )

const server = http.createServer((req) => {
    console.log(router.lookup(req.method, req.url))
})

server.listen(3000, err => {
    http.get('http://localhost:3000' + '/‣PRC⁑', (res) => {})
})

```

**Comment by mav-rik** [comment]
> ```js
> const http = require('http')
> const { ProstoRouter } = require('@prostojs/router')
> 
> const router = new ProstoRouter()
> 
> router.on('GET', '/%', () => 'ok' )
> 
> const server = http.createServer((req) => {
>     console.log(router.lookup(req.method, req.url))
> })
> 
> server.listen(3000, err => {
>     http.get('http://localhost:3000' + '/‣PRC⁑', (res) => {})
> })
> ```

So? It was transformed to `%E2%80%A3PRC%E2%81%91` first before request was sent. Then during handling it was decoded once and interpreted as `%` as I mentioned that in this particular implementation `%` and `‣PRC⁑` are synonyms.
No double decoding possible. I find this as an expected behavior.

The only thing I would do is to try to think of better combination for `‣PRC⁑` in order to prevent potential collisions with some real routs. or it can be even one character like `‱`. And this will be the limitation of this lib: the `%` and the `‱` are synonyms.

**Comment by ivan-tymoshenko** [comment]
> Secondly, as I told you I can put this combination manually instead of "%" to get through some security filters.

.

**Comment by ivan-tymoshenko** [comment]
```js
'use strict'

const http = require('http')
const express = require('express')
const app = express()

app.use((req, res, next) => {
  if (req.url === '/only-admin-path/%') {
      console.log('Only admin access!!!')
  }
  next()
})

app.get('/only-admin-path/%')

app.listen(3000)

http.get('http://localhost:3000' + '/only-admin-path/%', (res) => {})
http.get('http://localhost:3000' + '/only-admin-path/‣PRC⁑', (res) => {})
```

**Comment by ivan-tymoshenko** [comment]
This is an example of what I mean.

```js
'use strict'

const http = require('http')
const express = require('express')
const app = express()

app.use((req, res, next) => {
  if (req.url === '/only-admin-path/%') {
      console.log('Only admin access!!!')
  }
  next()
})

app.get('/only-admin-path/%', () => {
    console.log('Hello admin!')
})

app.listen(3000)

http.get('http://localhost:3000' + '/only-admin-path/%', (res) => {})
http.get('http://localhost:3000' + '/only-admin-path/‣PRC⁑', (res) => {})
```

**Comment by mav-rik** [comment]
@ivan-tymoshenko  I agree the solution I provided is not perfect and I agree it has the downside you described.

This kept me busy trying to again bring a better solution.

Now:
1) when registering route I replace `%` with `%25`
2) when normalizing URI on `lookup` I replace `%25` with `%2525`
3) everything works fine

This time I can't think of any downsides here.
Please use your critical thinking to find any issues with this approach.
Deployed as v0.0.11

**Comment by mav-rik** [comment]
> Actually, I like this one. I will think about it. Thanks for your help.
> 
> Maybe it will make sense to implement a custom decodeURI function that will decode everything except "%25" instead of encoding + decoding '%25'. It can be faster, but I'm not sure.

AFAK the `decodeURI` is already pretty fast. I doubt you can rewrite it in JS in any better way. Please keep me posted if you find more optimal way.
